language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '9'
  - '8'
  - '6'
branches:
  only:
    - master
    - /^greenkeeper.*$/

before_install:
  - ./scripts/run-on-latest-node.sh "npm install -g greenkeeper-lockfile@1"

before_script:
  - ./scripts/run-on-latest-node.sh "greenkeeper-lockfile-update"

script:
  - npm run verify

after_success:
  - npm install -g travis-deploy-once@4
  - travis-deploy-once "npm run semantic-release"
  - ./scripts/run-on-latest-node.sh "npm install --no-save coveralls && npm run coveralls"
  - ./scripts/run-on-latest-node.sh "npm install --no-save codecov && npm run codecov"

after_script:
  - ./scripts/run-on-latest-node.sh "greenkeeper-lockfile-upload"
