language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '11'
  # - '10'
  # - '8'
  # - '6'
branches:
  only:
    - master
    - /^greenkeeper.*$/

script:
  - npm run verify

after_success:
  - ./scripts/run-on-node-version.sh latest "npm install --no-save coveralls && npm run coveralls"
  - ./scripts/run-on-node-version.sh latest "npm install --no-save codecov && npm run codecov"
