ignores:
  - '@commitlint/*'
  - '@semantic-release/*'
  - '@size-limit/*'
  - '@swc/core'
  - '@types/*'
  - '@vitest/*'
  - clean-webpack-plugin
  - param-case
  - pascal-case
  - rimraf # false positive
  - semantic-release
  - source-map-loader
  - ts-loader
  - tslib
  - vitest
  - webpack-*
